### ISSUE TITLE
GameObject image link not working

### ISSUE THREAD

**Issue by rizmyabdulla** [lil-shake-code/helicity.ai#3]
This image link is not working on Gameobject.js file - https://us-central1-ai-game-maker.cloudfunctions.net/api/Image

Replace this image link with a valid image link.

**Comment by lil-shake-code** [comment]
That is a POST endpoint, you cannot GET on it actually. So it works only through the web app once you're logged in. Honestly, Dall E is too expensive, so might use a different link soon!
